# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  Version.Revision: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]
  MajorVersion: 1
  MinorVersion: 1

name: '$(Build.DefinitionName) $(MajorVersion).$(MinorVersion).$(Date:yy)$(DayOfYear).$(Version.Revision)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: Hands-on lab/lab-files/

- task: Docker@2
  displayName: Docker Build and Push to Azure CR
  inputs:
    containerRegistry: 'bestforyouazurecr'
    repository: 'best-for-you-organics'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.BuildId)


  