# multi-stage yaml pipelines
# build-test-staging-prod pipeline

variables:
  Version.Revision: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]
  VersionMajor: 1
  VersionMinor: 0

name: '$(Build.DefinitionName) $(VersionMajor).$(VersionMinor).$(Date:yy)$(DayOfYear).$(Version.Revision)'

# Only run against master
trigger:
- master

# Don't run against pull requests (PRs)
pr: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'Hands-on lab/lab-files'
        displayName: 'npm install' 

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'Hands-on lab/lab-files'
          customCommand: 'run build'
        displayName: 'npm run build'

      - task: Docker@2
        displayName: Docker Build and Push to Azure CR
        inputs:
          containerRegistry: 'bestforyouazurecr'
          repository: 'best-for-you-organics'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: $(Build.BuildId)
      
- stage: unittests
  dependsOn: build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo 'If I had some unit tests we would execute them here :) '
    
- stage: dev
  dependsOn: unittests
  jobs:
  - deployment: dev
    displayName: 'Deploy DEV'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'npm-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy docker container to DEV WebApp or SLOT'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: best-for-you-app-wm-dev-wac'
            inputs:
                azureSubscription: 'MCW-OSS-PAAS-DevOps'
                appType: webAppContainer
                WebAppName: 'best-for-you-app-wm-dev-wac'
                DockerNamespace: bestforyouregistrywm.azurecr.io
                DockerRepository: 'best-for-you-organics'
                DockerImageTag: latest

- stage: test
  dependsOn: dev
  jobs:
  - deployment: test
    displayName: 'Deploy to TEST'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'npm-test'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy container to test slot/webapp'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: best-for-you-app-wm-test-wac'
            inputs:
                azureSubscription: 'MCW-OSS-PAAS-DevOps'
                appType: webAppContainer
                WebAppName: 'best-for-you-app-wm-test-wac'
                DockerNamespace: bestforyouregistrywm.azurecr.io
                DockerRepository: 'best-for-you-organics'
                DockerImageTag: latest

- stage: uat
  dependsOn: test
  jobs:
  - deployment: uat
    displayName: 'Deploy to UAT'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'npm-uat'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy container to uat slot/webapp'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: best-for-you-app-wm-uat-wac'
            inputs:
                azureSubscription: 'MCW-OSS-PAAS-DevOps'
                appType: webAppContainer
                WebAppName: 'best-for-you-app-wm-uat-wac'
                DockerNamespace: bestforyouregistrywm.azurecr.io
                DockerRepository: 'best-for-you-organics'
                DockerImageTag: latest

- stage: preprod
  dependsOn: uat
  jobs:
  - deployment: preprod
    displayName: 'Deploy to Pre-Prod'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'npm-ppe'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy container to ppe slot/webapp'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: best-for-you-app-wm-ppe-wac'
            inputs:
                azureSubscription: 'MCW-OSS-PAAS-DevOps'
                appType: webAppContainer
                WebAppName: 'best-for-you-app-wm-ppe-wac'
                DockerNamespace: bestforyouregistrywm.azurecr.io
                DockerRepository: 'best-for-you-organics'
                DockerImageTag: latest

- stage: production
  dependsOn: preprod
  jobs:
  - deployment: production
    displayName: 'Deploy to Production'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'npm-prod'  
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy container to prodution slot/webapp'
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: best-for-you-app-wm'
            inputs:
                azureSubscription: 'MCW-OSS-PAAS-DevOps'
                appType: webAppContainer
                WebAppName: 'best-for-you-app-wm'
                DockerNamespace: bestforyouregistrywm.azurecr.io
                DockerRepository: 'best-for-you-organics'
                DockerImageTag: latest
